### ISSUE TITLE
About Setup Instructions

### ISSUE THREAD

**Issue by melikechan** [tqwei05/PlantSeg#2]
Hello, I've been impressed to see such a neat dataset and wanted to experiment.

However, I have experienced problems running in my environment. I have applied all three steps.

For example, when I execute `run.sh`, I get the following errors:
```
/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/optim/optimizer/zero_optimizer.py:11: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import \
Traceback (most recent call last):
  File "/home/melikechan/git-repos/PlantSeg/tools/train.py", line 104, in <module>
    main()
  File "/home/melikechan/git-repos/PlantSeg/tools/train.py", line 58, in main
    cfg = Config.fromfile(args.config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/config/config.py", line 460, in fromfile
    lazy_import is None and not Config._is_lazy_import(filename):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'configs/deeplabv3/deeplabv3_r50-d8_4xb4-40k_plantseg115-512x512.py'
/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/optim/optimizer/zero_optimizer.py:11: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import \
Traceback (most recent call last):
  File "/home/melikechan/git-repos/PlantSeg/tools/train.py", line 104, in <module>
    main()
  File "/home/melikechan/git-repos/PlantSeg/tools/train.py", line 58, in main
    cfg = Config.fromfile(args.config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/config/config.py", line 460, in fromfile
    lazy_import is None and not Config._is_lazy_import(filename):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'configs/deeplabv3/deeplabv3_r101-d8_4xb4-40k_plantseg115-512x512.py'
/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/optim/optimizer/zero_optimizer.py:11: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import \
Traceback (most recent call last):
  File "/home/melikechan/git-repos/PlantSeg/tools/train.py", line 104, in <module>
    main()
  File "/home/melikechan/git-repos/PlantSeg/tools/train.py", line 58, in main
    cfg = Config.fromfile(args.config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/config/config.py", line 460, in fromfile
    lazy_import is None and not Config._is_lazy_import(filename):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'configs/deeplabv3plus/deeplabv3plus_r50-d8_4xb4-40k_plantseg115-512x512.py'
/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/optim/optimizer/zero_optimizer.py:11: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import \
Traceback (most recent call last):
  File "/home/melikechan/git-repos/PlantSeg/tools/train.py", line 104, in <module>
    main()
  File "/home/melikechan/git-repos/PlantSeg/tools/train.py", line 58, in main
    cfg = Config.fromfile(args.config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/config/config.py", line 460, in fromfile
    lazy_import is None and not Config._is_lazy_import(filename):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'configs/deeplabv3plus/deeplabv3plus_r101-d8_4xb4-40k_plantseg115-512x512.py'
/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/optim/optimizer/zero_optimizer.py:11: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import \
Traceback (most recent call last):
  File "/home/melikechan/git-repos/PlantSeg/tools/train.py", line 104, in <module>
    main()
  File "/home/melikechan/git-repos/PlantSeg/tools/train.py", line 58, in main
    cfg = Config.fromfile(args.config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/config/config.py", line 460, in fromfile
    lazy_import is None and not Config._is_lazy_import(filename):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'configs/san/san_b16_plantseg115.py'
/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/optim/optimizer/zero_optimizer.py:11: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import \
Traceback (most recent call last):
  File "/home/melikechan/git-repos/PlantSeg/tools/train.py", line 104, in <module>
    main()
  File "/home/melikechan/git-repos/PlantSeg/tools/train.py", line 58, in main
    cfg = Config.fromfile(args.config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/config/config.py", line 460, in fromfile
    lazy_import is None and not Config._is_lazy_import(filename):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'configs/san/san_l14_plantseg115.py'
/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/optim/optimizer/zero_optimizer.py:11: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import \
Traceback (most recent call last):
  File "/home/melikechan/git-repos/PlantSeg/tools/train.py", line 104, in <module>
    main()
  File "/home/melikechan/git-repos/PlantSeg/tools/train.py", line 58, in main
    cfg = Config.fromfile(args.config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/config/config.py", line 460, in fromfile
    lazy_import is None and not Config._is_lazy_import(filename):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melikechan/anaconda3/envs/openmmlab/lib/python3.12/site-packages/mmengine/config/config.py", line 1661, in _is_lazy_import
    with open(filename, encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'configs/segnext/segnext_mscan-l_1xb16-adamw-40k_plantseg115-512x512.py'
```

or when I ran `setup.py`, I get following errors:
```
Traceback (most recent call last):
  File "/home/melikechan/git-repos/PlantSeg/setup.py", line 193, in <module>
    'all': parse_requirements('requirements.txt'),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melikechan/git-repos/PlantSeg/setup.py", line 97, in parse_requirements
    packages = list(gen_packages_items())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melikechan/git-repos/PlantSeg/setup.py", line 85, in gen_packages_items
    for info in parse_require_file(require_fpath):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melikechan/git-repos/PlantSeg/setup.py", line 81, in parse_require_file
    yield from parse_line(line)
  File "/home/melikechan/git-repos/PlantSeg/setup.py", line 50, in parse_line
    for info in parse_require_file(target):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melikechan/git-repos/PlantSeg/setup.py", line 77, in parse_require_file
    with open(fpath) as f:
         ^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'requirements/optional.txt'
```

When I looked at [MMSegmentation](https://github.com/open-mmlab/mmsegmentation) repository, I was able to see that these files are related to MMSegmentation and installed from the source. And still getting these errors.

Seems like I am missing something, however can't address it. Is there a chance to get more detailed setup instructions?

**Comment by tqwei05** [comment]
Hello,
I have added the necessary configuration files to the config directory. To set up the environment, please follow the instructions in the mmseg repository to build the conda environment first.

**Comment by melikechan** [comment]
> Hello, I have added the necessary configuration files to the config directory. To set up the environment, please follow the instructions in the mmseg repository to build the conda environment first.

Alright, it works now!

**Comment by melikechan** [comment]
For anyone who gets _dataset error_:
**Solution 1:**
- Add PlantSeg-related files in `/mmseg/dataset` to your **mmsegmentation** installation's  `/mmseg/dataset`  directory and to `__init__.py`.
- `export PYTHONPATH="$(pwd)"` (see https://github.com/open-mmlab/mmsegmentation/issues/1622#issuecomment-1140404502) (I was unable to execute in Google Colab, probably I did something wrong)
